services:
  unshackledword.tooling.database:
    image: postgres:18
    container_name: postgres-test-db
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-postgres}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-test}
    ports:
      - "5432:5432"
    volumes:
      - unshackled_postgres:/var/lib/postgresql/data

  unshackledword.tooling.db-migration:
    #image: unshackledword.migration.postgres
    depends_on:
      - unshackledword.tooling.database
    build:
      context: .
      dockerfile: src/UnshackledWord.Tooling.Postgres.Migration/Dockerfile
    environment:
      - UNSHACKLEDWORD_ENVIRONMENT=${ENVIRONMENT}
      - UNSHACKLEDWORD_CONNECTIONSTRINGS__POSTGRESCONNECTION=${POSTGRES_CONNECTIONSTRING}

  unshackledword.tooling.seed-db:
    #image: unshackledword.tooling.seeddb
    depends_on:
      - unshackledword.tooling.database
      - unshackledword.tooling.db-migration
    build:
      context: .
      dockerfile: src/UnshackledWord.Tooling.SeedDb/Dockerfile
    user: "1000:1000"
    environment:
      - UNSHACKLEDWORD_ENVIRONMENT=${ENVIRONMENT}
      - UNSHACKLEDWORD_CONNECTIONSTRINGS__POSTGRESCONNECTION=${POSTGRES_CONNECTIONSTRING}
      - UNSHACKLEDWORD_APPSETTINGS__DATABASESEEDING__SOLUTIONTEMPPATH=${SOLUTIONTEMPPATH:-/src/temp}
      - UNSHACKLEDWORD_APPSETTINGS__DATABASESEEDING__SOLUTIONASSETSPATH=${SOLUTIONASSETSPATH:-/src/assets}
    volumes:
      - ./assets:/src/assets
      - ./temp:/src/temp
# docker run -it --entrypoint /bin/bash unshackledword.tooling.seed-db

  unshackledword.tooling.webapi:
    #image: unshackledword.tooling.webapi
    depends_on:
      - unshackledword.tooling.database
      - unshackledword.tooling.seed-db
      - unshackledword.tooling.db-migration
    build:
      context: .
      dockerfile: src/UnshackledWord.Tooling.WebApi/Dockerfile
    ports:
      - "7654:8080"
    environment:
      - UNSHACKLEDWORD_ENVIRONMENT=${ENVIRONMENT}
      - UNSHACKLEDWORD_CONNECTIONSTRINGS__POSTGRESCONNECTION=${POSTGRES_CONNECTIONSTRING}

  unshackledword.tooling.bibletagger:
    #image: unshackledword.tooling.bibletagger
    build:
      context: .
      dockerfile: src/UnshackledWord.Tooling.BibleTagger/Dockerfile
    ports:
      - "8765:8080"
    depends_on:
      - unshackledword.tooling.webapi
    environment:
      - UNSHACKLEDWORD_ENVIRONMENT=${ENVIRONMENT}
      - UNSHACKLEDWORD_APIURL=http://unshackledword.tooling.webapi:8080/api

volumes:
  unshackled_postgres:
