services:
  unshackledword.tooling.database:
    image: postgres:latest
    container_name: postgres-test-db
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-postgres}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-test}
    ports:
      - "5432:5432"
#    volumes:
#      - ./temp/postgres_data:/var/lib/postgresql/data

  unshackledword.tooling.db-migration:
    #image: unshackledword.migration.postgres
    build:
      context: .
      dockerfile: src/UnshackledWord.Tooling.Postgres.Migration/Dockerfile
    environment:
      - UNSHACKLEDWORD_ENVIRONMENT=${ENVIRONMENT}
      - UNSHACKLEDWORD_CONNECTIONSTRINGS__POSTGRESCONNECTION=${POSTGRES_CONNECTIONSTRING}

  unshackledword.tooling.seed-db:
    #image: unshackledword.tooling.seeddb
    build:
      context: .
      dockerfile: src/UnshackledWord.Tooling.SeedDb/Dockerfile
    depends_on:
      - unshackledword.tooling.db-migration
    environment:
      - UNSHACKLEDWORD_ENVIRONMENT=${ENVIRONMENT}
      - UNSHACKLEDWORD_CONNECTIONSTRINGS__POSTGRESCONNECTION=${POSTGRES_CONNECTIONSTRING}
      - UNSHACKLEDWORD_APPSETTINGS__DATABASESEEDING__ELBERFELDER1871TEXTFILE=${ELBERFELDER1871TEXTFILE:-/src/assets/elberfelder1871-theword-export.txt}

  unshackledword.tooling.webapi:
    #image: unshackledword.tooling.webapi
    build:
      context: .
      dockerfile: src/UnshackledWord.Tooling.WebApi/Dockerfile
    ports:
      - "7654:8080"
    depends_on:
      - unshackledword.tooling.seed-db
    environment:
      - UNSHACKLEDWORD_ENVIRONMENT=${ENVIRONMENT}
      - UNSHACKLEDWORD_CONNECTIONSTRINGS__POSTGRESCONNECTION=${POSTGRES_CONNECTIONSTRING}

  unshackledword.tooling.bibletagger:
    #image: unshackledword.tooling.bibletagger
    build:
      context: .
      dockerfile: src/UnshackledWord.Tooling.BibleTagger/UnshackledWord.Tooling.BibleTagger/Dockerfile
    ports:
      - "8765:8080"
    depends_on:
      - unshackledword.tooling.webapi
    environment:
      - UNSHACKLEDWORD_ENVIRONMENT=${ENVIRONMENT}
      - UNSHACKLEDWORD_APIURL=http://unshackledword.tooling.webapi:8080/api

  unshackledword.tooling.bibletagger.client:
    #image: unshackledword.tooling.bibletagger.client
    build:
      context: .
      dockerfile: src/UnshackledWord.Tooling.BibleTagger/UnshackledWord.Tooling.BibleTagger.Client/Dockerfile
    ports:
      - "8765:8080"
    depends_on:
      - unshackledword.tooling.webapi
    environment:
      - UNSHACKLEDWORD_ENVIRONMENT=${ENVIRONMENT}
      - UNSHACKLEDWORD_APIURL=http://unshackledword.tooling.webapi:8080/api

