@WebApi_HostAddress = http://localhost:5142/api

GET {{WebApi_HostAddress}}/elberfelder/bookId/1/chapterId/1/verseId/1
Accept: application/json

###

GET {{WebApi_HostAddress}}/elberfelder/chapterText/bookId/1/chapterId/1
Accept: application/json

###

GET {{WebApi_HostAddress}}/elberfelder/chapterWords/bookId/1/chapterId/1
Accept: application/json

###
