<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <UserSecretsId>dotnet-UnshackledWord.Tooling.SeedDb-ff6e585f-9657-42a0-905e-72d15cbc893f</UserSecretsId>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="coverlet.collector"/>
        <PackageReference Include="Microsoft.NET.Test.Sdk"/>
        <PackageReference Include="xunit.v3"/>
        <PackageReference Include="xunit.runner.visualstudio"/>
    </ItemGroup>

    <ItemGroup>
        <Using Include="Xunit"/>
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\UnshackledWord.Tooling.SeedDb\UnshackledWord.Tooling.SeedDb.csproj" />
    </ItemGroup>

</Project>
