<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Google.GenAI" />
    <PackageReference Include="Polly" />
    <PackageReference Include="Serilog.AspNetCore"/>
    <PackageReference Include="Serilog.Sinks.Async"/>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\UnshackledWord.Tooling.WebApi\UnshackledWord.Tooling.WebApi.csproj"/>
  </ItemGroup>

</Project>
